### ISSUE TITLE
Compression of ubxtool stream

### ISSUE THREAD

**Issue by ptudor** [ahupowerdns/galmon#101]
Is the stream of data collected by ubxtool compressed on its way to navrecv?

A central navrecv host might have more CPU than bandwidth and benefit from compression.

A remote ubxtool host might have a metered connection that is shared or a latent connection where less packets transmitted are less packets lost.

Accommodating those who like to tune the knobs, allowing a client to pick the preferred compression level can allow for variation between the slowest embedded processors and fastest workstations.

Reference: [5 ways Facebook improved compression at scale with Zstandard
](https://engineering.fb.com/core-data/zstandard/)

**Comment by ahupowerdns** [comment]
i'm all for it, we need to measure how well zstd does if we force it to emit every message as a chunck though. We can't buffer a lot.

**Comment by ptudor** [comment]
Most of my streams are around 20% of their original size. It's great.

Added in e96ceb7ddd0df0e498abcbc24d1c2a645360f17b 
Described in 53f91088e02bdf7aeed5ba1f272b0f0766a32ae4
Memory tuning in bdc1c0830c224d8807ccf58f3c2ca27b6c582d76
RNIE00000000 in 7c8ac749f7ff06ae0ccd11facf6b7ca4ef5dc514
