### ISSUE TITLE
/run/ubxtool is deleted on every startup

### ISSUE THREAD

**Issue by kiwibrew** [ahupowerdns/galmon#23]
On Raspbian (maybe all Debian) it's expected that subdirectories of /run (/var/run) are deleted on reboot by systemd. So our current instructions for establishing a systemd service - which tell us to mkdir /run/ubxtool result in a service definition that doesn't survive reboot. If we use WorkingDirectory=/run/ it survives reboot. @mahtin what do you think? Ok to change WorkingDirectory to /run/ or should we establish that directory in a supported way?

**Comment by mahtin** [comment]
Yes. The submitted update was documented as `This is very much a first stab.` and hence could do with some additional love. I agree with the directory comment and the creation of `/run/ubxtool`.

There's a `ExecStartPre=/bin/mkdir -p /run/ubxtool` commands; but maybe some more commands are needed to fix this conflict. 

I will admit that `systemd` isn't my forte. Please feel free to update/replace/improve/etc my scripts and config file. I'll admit right now; the install is not perfect in any way.

**Comment by amontefusco** [comment]
Solved in #36.

**Comment by akhepcat** [comment]
Just created a pull request for some additional cleanup and rework here.
