### ISSUE TITLE
allow stations to name themselves

### ISSUE THREAD

**Issue by mahtin** [ahupowerdns/galmon#32]
Presently the `ubxtool` requires the `--station` command (a number between 1 and N) which identifies a unique station. Let's upgrade that to a number colon name so that the database has a station identifier. (in my case, I'd use my ham radio callsign; but maybe someone wants to use their name or city.
For example ...
```
     $ ubxtool ... --station 5:W6LHI ...
```
... in my case. This would be backward compatible because if no name was provided; then it's simply `""`.
The name would only need to be sent once to the database; leaving all other messages to simple use the `g_srcid` in the regular `NavMonMessage` messages.

**Comment by ahupowerdns** [comment]
--owner and --remark deliver this now.
