### ISSUE TITLE
duplicate ubxtool

### ISSUE THREAD

**Issue by garyemiller** [ahupowerdns/galmon#33]
The gpsd project has shipped a ubxtool since September 2018.  A very different thing than your ubxtool.

The gpsd project is adding link in their README to this project to lessen confusion.  Can galmon please add a link back to our ubxtool?

**Comment by mahtin** [comment]
@garyemiller - can you provide URLs?

**Comment by garyemiller** [comment]
https://gpsd.io

https://gpsd.io/ubxtool.html

Which are currently using gitlab as primary repository.

**Comment by ahupowerdns** [comment]
added a link, apologies for the confusion! We're pondering a new name but have not yet settled on one.
