### ISSUE TITLE
Two bugs in ubxtool.sh

### ISSUE THREAD

**Issue by amontefusco** [ahupowerdns/galmon#36]
I found two small bugs in ubxtool.sh, the following patch fix them:

```
-DEV="/run/ubxtool"
+DIR="/run/ubxtool"
 
-STATION="`/usr/local/ubxtool/station`"
+STATION="`cat /usr/local/ubxtool/station`"
```

**Comment by ahupowerdns** [comment]
hi - odd that that crept in there. Can you check if  91df9d430d5da0157dcaa0ed3a73b61b5140e3b2 got it right?

**Comment by amontefusco** [comment]
There is even another one.
In the script, the /var/ubxtools is created each time the script is started by the systemd service.
However, it seems that, because that dir is mentioned as WorkingDirectory in systemd services file, that causes an error.

See also

https://www.techchorus.net/blog/systemd-unit-file-just-to-create-a-directory-under-run/

**Comment by amontefusco** [comment]
The changes below solve the issue:

ubxtool.service:

-#RuntimeDirectory=ubxtool
+RuntimeDirectory=ubxtool

ubxtool.sh
-mkdir ${DIR}
