### ISSUE TITLE
Resolution of observed SV azi/elev is too high in observers.json

### ISSUE THREAD

**Issue by philcrump** [ahupowerdns/galmon#49]
Resolution of the values should be reduced, both for served filesize efficiency, and to prevent a determined party from reverse-engineering the exact location of an observer station.

eg.
https://galmon.eu/observers.json: `G20@0":{"age-s":39,"azi":249.45191412415818,"db":22,"elev":5.876863024662498, ` ...

**Comment by nousian** [comment]
I think for the second issue it won't fully help, a determined party could (easily?) and accurately average the azi/elev -angles over time to reverse-engineering the exact location of the observer station?

**Comment by philcrump** [comment]
Indeed, it would only increase the difficulty. I think there's always going to be a limit to how much you can obscure in useful observations of a navigation service.
