### ISSUE TITLE
GIT observer information doesn't match published web version

### ISSUE THREAD

**Issue by akhepcat** [ahupowerdns/galmon#67]
For example,  currently on the published site:
https://galmon.eu/observer.html?observer=38

I can see owner, remark, uptime, mods, vendor, and other fields.

The current GIT  version of the html site does not provide this information, which would be nice to have for our self-hosted versions  (see:  https://www.denali.net/galmon/observer.html?observer=38   for comparison)

**Comment by nousian** [comment]
I've noticed the same. Would be nice to have the same/latest/current version for private hosting/testing.

BTW your self-hosted version seems to be lacking recent TLE-files, or at least it does not match any TLE-positions on "best-tle" -field? I checked as I've had some problems lately with wildly incorrect TLE-matches, where matched object is wrong and distance is like 10000+ km...

**Comment by nousian** [comment]
Also the public json-format seems to differ a bit from self-compiled and hosted one. For example there is "qi"-field present in svs.json on published web version, that is not present on self-hosted one.

Bumped into this while trying to parse and compare the public data vs. own self-generated feed.

**Comment by akhepcat** [comment]
> BTW your self-hosted version seems to be lacking recent TLE-files, or at least it does not match
>any TLE-positions on "best-tle" -field? I checked as I've had some problems lately with wildly
> incorrect TLE-matches, where matched object is wrong and distance is like 10000+ km...

Turns out I just never ran the update_tles script.  that wasn't really pressing for the issue at hand though it's now taken care of.

**Comment by ahupowerdns** [comment]
AFAIK all these changes have now been committed.

**Comment by akhepcat** [comment]
great stuff, thanks!

needed to restart all the NAV servers and reload my tabs and then it was all good.
