### ISSUE TITLE
[INFO] [SOLVED] Can be the position and timestamp NMEA messages printed in cleartext in the stdout ?

### ISSUE THREAD

**Issue by amontefusco** [ahupowerdns/galmon#74]
The purpose would be to use the same systems as NTP and position server, whilst ubxtool is running.

**Comment by nousian** [comment]
There seems to be:

'''app.add_flag("--keep-nmea,-k", doKeepNMEA, "Don't disable NMEA");'''

Flag already, you've tried that?

Also as default enabled "UBX-NAV-POSECEF" and "UBX-NAV-PVT" messages contain position information? They are pretty straightforward to decode. Message format is in:

https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf

BTW, for NTP-timing if you want accuracy you should consider using PPS-signal from receiver. Serial port read NMEA-derived time is not that very accurate.

**Comment by nousian** [comment]
There seems to already be option for that:

'''app.add_flag("--keep-nmea,-k", doKeepNMEA, "Don't disable NMEA");'''

You've tried that?

Also postion is included in already enabled "UBX-NAV-POSECEF" and "UBX-NAV-PVT" messages, they are straightforward to decode:

https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf

BTW, for NTP timing receivers PPS signal gives much higher accuracy than serial read NMEA.

**Comment by nousian** [comment]
Hmm... it just occured to me you would most likely need the NMEA/UBX -messagestream in unmodified form, "tapped" direct from serial input and sent onwards in some form. I've been thinking the same, but for raw messages to be fed to RTKLIB, so the same receiver could be used as RTK-basestation at the same time.

**Comment by amontefusco** [comment]
> There seems to already be option for that:
> 
> app.add_flag("--keep-nmea,-k", doKeepNMEA, "Don't disable NMEA");
> 
> You've tried that?

yes, I did but I was unable to find WHERE that stuff is kept.

> BTW, for NTP-timing if you want accuracy you should consider using PPS-signal from receiver. Serial port read NMEA-derived time is not that very accurate.

I'm very aware about that stuff (ntpd config and PPS detection using pps-gpio kernel module).
Indeed my question here is meant to understand if I can use the same (valuable) GNSS receiver both for GALMON network and ntpd synch.

**Comment by amontefusco** [comment]
And, as you mentioned, the ntpd would like to read regular ASCII NMEA sentences, so probably there is no way, apart buy another ZED breakout board.

**Comment by nousian** [comment]
Sure it is doable, I'll look into this.

Start looks promising, with interceptty I managed easily to "tap" serial port traffic to/from receiver:

'''sudo interceptty -s 'ispeed 230400 ospeed 230400' -l /dev/ttyACM0 /dev/ttyDUMMY'''

https://github.com/geoffmeyers/interceptty/blob/master/interceptty

ubxtool is then connected to this:

'''./ubxtool --wait --port /dev/ttyDUMMY'''

Then next step is to strip extra padding and feed that into program parsing it.

**Comment by nousian** [comment]
And for NTPD, would PPS-signal suffice by itself? After setting the initial time, that is?

**Comment by amontefusco** [comment]
> And for the NTPD, would a PPS-signal suffice by itself? After setting the initial time, that is?

As per current implementation, ntpd needs a continuous stream of NMEA messages.

**Comment by amontefusco** [comment]
> Sure it is doable, I'll look into this.

It seems that -k is acting in such a way that the receiver is configured to provide info **both** as per NMEA ASCII protocol and a binary (proprietary?) protocol.

At this point, the NMEA is readable just with proper use of ncat/nc utility, using the pseudo-tty usual trick..

**Comment by nousian** [comment]
Which reveiver are you using? I do not seem to be able to enable NMEA-messages with F9P, even with -k option there are no NMEA messages in the tapped stream. UBX raw messages yes, so the tapping works fine. I have to search one of my old F8s and try with that.

I believe USB/serial device sharing is not that well defined in Linux, so behaviour might be not so predictable. The jitter might be because of this maybe? Though should the use of PPS signal fix this jitter as well, if it is just on the serial message?

**Comment by nousian** [comment]
From your previous post I am guessing F8, correct?

I have one somewhere, just have to find it. But definitely my F9 is not outputting any NMEA right now with -k flag or not.

**Comment by amontefusco** [comment]
I have a ublox ZED-F9P and NEO-M8N-0.  
I have to check the ZED.

**Comment by akhepcat** [comment]
for the F9P,  if you're using the USB output for normal signals, you *should* be able to add a ttl-usb adapter onto UART2  of the F9P  board and feed that separately into ntpd.

* this is based on a convo had with remco on the #galileo channel - i haven't yet tried it, but will be doing so later this week.

**Comment by nousian** [comment]
With at least C099-F9P evaluation board you can also route (different) messages via i2c to bluetooth/wifi.

**Comment by amontefusco** [comment]
> Which receiver are you using? I do not seem to be able to enable NMEA-messages with F9P, even with -k option there seems to be no NMEA messages in the tapped stream - haven't parsed it though but looking the stream with hexdump it seems so.

You are right, even with -k option, the F9P doesn't emit NMEA messages interspersed with the binary stream.

**Comment by amontefusco** [comment]
> for the F9P, if you're using the USB output for normal signals, you should be able to add a ttl-usb adapter onto UART2 of the F9P board and feed that separately into ntpd.

From a quick test, it seems that even there (RX2/RX1) there are the same binary messages, not NMEA ones.

**Comment by akhepcat** [comment]
> > for the F9P, if you're using the USB output for normal signals, you should be able to add a ttl-usb adapter onto UART2 of the F9P board and feed that separately into ntpd.
> 
> From a quick test, it seems that even there (RX2/RX1) there are the same binary messages, not NMEA ones.

ah, yes - you may need to use ucenter to enable the messaging;  though that should have read UART1.

UART1 can be used for host messaging (as can USB)  but UART2  cannot be for host messaging.   It seems like you *can* enable NMEA on UART2 - but UART1  is probably the better choice.

**Comment by amontefusco** [comment]
> ah, yes - you may need to use ucenter to enable the messaging; though that should have read UART1.

You are right, I twiggled with parameters in Windows ucenter 19 and now I get on UART1 (dubbed TX1 on ArduSimple) the NMEA messages @38400 bps.

Thanks akhepcat and all for the support.

**Comment by amontefusco** [comment]
```
 ntpq -n -cpeers pine64.local                                           andrewp: Fri Jan 10 16:33:12 2020

     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
o127.127.20.0    .GPS.            0 l    3   16   77    0.000    0.030   0.008

```
