### ISSUE TITLE
/geo/ could remember preferences

### ISSUE THREAD

**Issue by jeffpc** [ahupowerdns/galmon#77]
Every time I go to /geo/, I do the same things:

1. disable coverage (1 click)
2. change the projection (2 clicks)

It'd be nice if the viewer remembered my preferences instead of having to click around to make the map readable (for me).

**Comment by mahtin** [comment]
This is an excellent idea. Code at https://github.com/ahupowerdns/galmon/pull/78/commits/71cd4ebefa1c48cdfb81a3d68ca378ecc2256779

**Comment by philcrump** [comment]
To tie the relevant PR: https://github.com/ahupowerdns/galmon/pull/78
